#!/bin/bash

# Loop through all user accounts starting with "stud"
for user in /home/stud*; do
  # Get the username from the user's home directory path
  username=$(basename "$user")

  # New home directory path
  new_home="/usr/$username"

  # Change the home directory path
  usermod -d "$new_home" "$username"

  # Change the password to "username123"
  echo -e "$username123\n$username123" | passwd "$username"
done
