#!/bin/bash

find_largest() {
  if (( $1 >= $2 && $1 >= $3 )); then
    echo $1
  elif (( $2 >= $1 && $2 >= $3 )); then
    echo $2
  else
    echo $3
  fi
}

read -p "Enter the first number: " num1
read -p "Enter the second number: " num2
read -p "Enter the third number: " num3
largest=$(find_largest $num1 $num2 $num3)


echo "The largest number among $num1, $num2, and $num3 is: $largest"
