#!/bin/bash


correct_username="your_username"
correct_password="your_password"
read -p "Username: " username
read -sp "Password: " password
echo


if [[ "$username" == "$correct_username" && "$password" == "$correct_password" ]]; then
  echo "Login successful. Welcome, $username!"
else
  echo "Login failed. Incorrect username or password."
fi
